name: Print pull request context
on: 
    pull_request:
        types: [opened, reopened, edited]
    workflow_dispatch: 
jobs:
  print-pr-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Context
        run: 
          echo "${{ toJson(github) }}" 